[build]
  command = "npm run build"
  publish = "dist/portfolio"
  
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/portfolio/assets/env.js,dist/portfolio/assets/runtime-env.js"
  NODE_VERSION = "18"

# This ensures that all routes get routed to index.html for Angular's router to handle
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Post-processing plugin
[[plugins]]
  package = "@netlify/plugin-inject-env-vars-in-html" 