[context.production.environment]
  # These are the variables that will be available at runtime
  # They will be injected by Netlify's runtime environment injection
  NG_APP_EMAILJS_SERVICE_ID = "${NG_APP_EMAILJS_SERVICE_ID}"
  NG_APP_EMAILJS_TEMPLATE_ID = "${NG_APP_EMAILJS_TEMPLATE_ID}"
  NG_APP_EMAILJS_PUBLIC_KEY = "${NG_APP_EMAILJS_PUBLIC_KEY}"

[context.deploy-preview.environment]
  NG_APP_EMAILJS_SERVICE_ID = "${NG_APP_EMAILJS_SERVICE_ID}"
  NG_APP_EMAILJS_TEMPLATE_ID = "${NG_APP_EMAILJS_TEMPLATE_ID}"
  NG_APP_EMAILJS_PUBLIC_KEY = "${NG_APP_EMAILJS_PUBLIC_KEY}"

[context.branch-deploy.environment]
  NG_APP_EMAILJS_SERVICE_ID = "${NG_APP_EMAILJS_SERVICE_ID}"
  NG_APP_EMAILJS_TEMPLATE_ID = "${NG_APP_EMAILJS_TEMPLATE_ID}"
  NG_APP_EMAILJS_PUBLIC_KEY = "${NG_APP_EMAILJS_PUBLIC_KEY}" 